version: '1.0'

services:
  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    image: demo-search-service:v1.0
    ports:
      - 8080:8080
      - 40000:40000
    extra_hosts:
      - host.docker.internal:host-gateway
  php-grpc-env:
    build:
      context: ./php_grpc_docker
      dockerfile: Dockerfile
    image: demo-php-grpc-env:v1.0
    ports:
      - 8081:8080
    restart: unless-stopped
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /var/www/
    volumes:
      - ./php_grpc_docker/:/var/www
      - ./protos/:/var/www/protos